AppVeterinariaUCR/Controllers/GaleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AppVeterinariaUCR.Controllers
{
	public class GaleryController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

AppVeterinariaUCR/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppVeterinariaUCR.Models;
using AppVeterinariaUCR.Data;
using Microsoft.IdentityModel;

//Librerias para utulizar la autenticacion por formulario
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;


namespace AppVeterinariaUCR.Controllers
{
    public class LoginController : Controller
    {
        private VeterinariaContext context;

        //Constructor con parametros que recibe la instancia contexto 
        public LoginController(VeterinariaContext cnt)
        {
            this.context = cnt;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind] Usuarios user)
        {
            try
            {
                var temp = this.ValidarUsuario(user);

                //se pregunta si el usuario se valido correctamente 
                if (temp != null)
                {
                    var userClaims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, temp.Login),
                        new Claim(ClaimTypes.Email, temp.Email),
                    };

                    var grandIdentity = new ClaimsIdentity(userClaims, "User Identity");

                    var userPrincipal = new ClaimsPrincipal(new[] { grandIdentity });

                    HttpContext.SignInAsync(userPrincipal);

                    return RedirectToAction("Index", "Home");
                }
                TempData["mensaje"] = "Error usurario o password incorrecto";
                return View(user);
            }
            catch (Exception)
            {

                throw;
            }
        }


        [HttpGet]
        public IActionResult CrearCuenta()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult CrearCuenta([Bind] Usuarios usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    usuario.Password = this.generarClave();

                    this.context.Usuarios.Add(usuario);

                    this.context.SaveChanges();

                    Email email = new Email();
                    email.enviar(usuario, @"wwwroot/css/img/FirmaVeterinaria.jpg");

                    TempData["mensaje"] = "Usuario creado correctamente.";

                    return RedirectToAction("CrearCuenta");
                }
                else
                {
                    TempData["mensaje"] = "No se logro crear el usuario";
                    return View(usuario);
                }

            }
            catch (Exception ex)
            {
                //TempData["mensaje"] = "Error " + ex.Message;
                TempData["mensaje"] = "El  usuario ya existe";
                return View(usuario);
            }


        }

        private string generarClave()
        {
            try
            {
                Random random = new Random();
                string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

                return new string(Enumerable.Repeat(chars, 12).Select(s => s[random.Next(s.Length)]).ToArray());
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        //Programacion del 31 de mayo hora 14:07
        private Usuarios ValidarUsuario(Usuarios temp)
        {
            Usuarios autorizado = null;

            //aqui se valida el login 
            var user = this.context.Usuarios.FirstOrDefault(u => u.Login == temp.Login);

            //aqui se pregunta si existe un usurio 
            if (user != null)
            {
                //se confirma la contrase;a
                if (user.Password.Equals(temp.Password))
                {
                    autorizado = user;
                }
            }

            return autorizado;

        }


        public  async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index","Home");

        }

        [HttpGet]
        public IActionResult cambioClave()
        {
            return View();
        }

        


    }
}

AppVeterinariaUCR/Controllers/MascotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppVeterinariaUCR.Data;
using AppVeterinariaUCR.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
namespace AppVeterinariaUCR
{
    //Class  MascotasController   hereda de controlador
    public class MascotasController : Controller
    {
        //variable _context  permite manejar la referencia con la Base Datos
        private readonly VeterinariaContext _context;

        //Constructor con parámetros  y recibe como argumento el contexto
        public MascotasController(VeterinariaContext context)
        {
            _context = context;
        }

        // GET: Mascotas
        //primer  método de ejecución  asincronico
        public async Task<IActionResult> Index()
        {
            //retorna  una vista
            return View(await _context.Mascotas.ToListAsync());
        }

        // GET: Mascotas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mascotas = await _context.Mascotas
                .FirstOrDefaultAsync(m => m.id == id);
            if (mascotas == null)
            {
                return NotFound();
            }

            return View(mascotas);
        }

        // GET: Mascotas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mascotas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,fechaIngreso,peso,raza,estado")] Mascotas mascotas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mascotas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mascotas);
        }

        // GET: Mascotas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mascotas = await _context.Mascotas.FindAsync(id);
            if (mascotas == null)
            {
                return NotFound();
            }
            return View(mascotas);
        }

        // POST: Mascotas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,fechaIngreso,peso,raza,estado")] Mascotas mascotas)
        {
            if (id != mascotas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mascotas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MascotasExists(mascotas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mascotas);
        }

        // GET: Mascotas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mascotas = await _context.Mascotas
                .FirstOrDefaultAsync(m => m.id == id);
            if (mascotas == null)
            {
                return NotFound();
            }

            return View(mascotas);
        }

        // POST: Mascotas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mascotas = await _context.Mascotas.FindAsync(id);
            _context.Mascotas.Remove(mascotas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MascotasExists(int id)
        {
            return _context.Mascotas.Any(e => e.id == id);
        }
    }
}

AppVeterinariaUCR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Veterinaria UCR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>


<body>

    <header>
        @*menu de opciones*@ 

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @*opcion principal*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Veterinaria Pacífico</a>
                
                @*boton del menú*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
                @*opciones del menú*@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*items del  menú de opciones*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @*if para habilitar opciones del menu solo si cuenta con una cuenta*@

                        @if (User.Identity.IsAuthenticated)
                        {
                            @*item Mascota*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Mascotas" asp-action="Index">Mascotas</a>
                            </li>
                            @*item productos*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                            </li>

                        }



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Galery" asp-action="Index">Galery</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*Submenu de opciones*@
                        <li class="nav-item dropdown">
                            @*item raiz*@
                            <a class=" nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#"
                               aria-haspopup="true" aria-expanded="false">Consultas</a>

                            @*Creamos los items*@
                            <div class="dropdown-menu">
                                <a class="dropdown-item nav-link text-dark" asp-area="" asp-action="GaleryProductos" asp-controller="Productos">Detalle de productos</a>
                                <a class="dropdown-item nav-link text-dark">Detalle Mascotas</a>
                                <a class="dropdown-item nav-link text-dark">Detalle Tratamiento</a>
                            </div>

                        </li>

                        @*Submenu de opciones para login*@
                    <li class="nav-item dropdown">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @*item raiz*@
                            <a class=" nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#"
                               aria-haspopup="true" aria-expanded="false">Hola @User.Identity.Name</a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item nav-link text-dark" asp-area="" asp-action="Logout" asp-controller="Login">Cerrar sesion</a>
                                <a class="dropdown-item nav-link text-dark" asp-controller="Login" asp-action="">Cambiar contraseña</a>
                            </div>



                        }
                        else
                        {
                            @*item raiz*@
                            <a class=" nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#"
                               aria-haspopup="true" aria-expanded="false">Perfil de usuario</a>
                            @*Creamos los items*@
                            <div class="dropdown-menu">
                                <a class="dropdown-item nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Login">Iniciar sesion</a>
                                <a class="dropdown-item nav-link text-dark" asp-controller="Login" asp-action="CrearCuenta">Registrarse</a>
                            </div>
                        }




                    </li>

                    </ul>
                </div>

            </div>
        </nav>

    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppVeterinariaUCR - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>